version: '3'

services:
  web:
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
    image: simple-ticketing:latest
    restart: on-failure
    ports:
      - 8080:80
    depends_on:
      - db
    hostname: simple-ticketing
    command: bash -c "./.docker/wait-for-it.sh -t 0 db:3306 && bin/console doctrine:migrations:migrate && apachectl -D FOREGROUND"
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    environment:
      - API_BASE_URL=http://localhost:8080/
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=simple_ticketing
  db:
    build:
      context: .
      dockerfile: .docker/db/Dockerfile
    image: db:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  swagger:
    image: swaggerapi/swagger-ui
    restart: on-failure
    ports:
      - '8082:8080'
    depends_on:
      - web
    environment:
      - API_URL= http://localhost:8080/doc/api-doc.yaml
volumes:
  vendor:
