post_login:
    path: /login
    controller: SimpleTicketing\Controller\LoginController::login
    methods: POST

post_tickets:
    path: /tickets
    controller: SimpleTicketing\Controller\TicketsController::postTicket
    methods: POST

get_tickets:
    path: /tickets
    controller: SimpleTicketing\Controller\TicketsController::getTickets
    methods: GET
