post_login:
    path: /login
    controller: SimpleTicketing\Controller\LoginController::login
    methods: POST

post_tickets:
    path: /tickets
    controller: SimpleTicketing\Controller\TicketsController::postTicket
    methods: POST

put_tickets:
    path: /tickets/{id}/messages
    controller: SimpleTicketing\Controller\TicketsController::putTicketMessage
    methods: PUT

get_tickets:
    path: /tickets
    controller: SimpleTicketing\Controller\TicketsController::getTickets
    methods: GET

get_tickets_id:
    path: /tickets/{id}
    controller: SimpleTicketing\Controller\TicketsController::getTicketById
    methods: GET